@server=http://localhost:3000
@createdHostId={{createNewHost.response.body.$.id}}

### GET all hosts
GET {{server}}/hosts

### GET host by id
GET {{server}}/hosts/1

### POST new host
# @name createNewHost
POST {{server}}/hosts
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.10"
}

### PUT update host by id
PUT {{server}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### DELETE host by id
DELETE {{server}}/hosts/{{createdHostId}}

